// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFJirKtKGe_kqiElReHdo4rtn3tdlQxYE',
    appId: '1:873399511180:web:065e1283bc7fb3a12d33a9',
    messagingSenderId: '873399511180',
    projectId: 'flutter-crud-64a1f',
    authDomain: 'flutter-crud-64a1f.firebaseapp.com',
    storageBucket: 'flutter-crud-64a1f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXbwSxT_M-NbX6NRDF9GBK5tFAOyxTiIU',
    appId: '1:873399511180:android:59bca7528dc478762d33a9',
    messagingSenderId: '873399511180',
    projectId: 'flutter-crud-64a1f',
    storageBucket: 'flutter-crud-64a1f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBO8DGvWMY1vfZ6TV2rwtI8is7gYxejm44',
    appId: '1:873399511180:ios:a62308e3d223b9bf2d33a9',
    messagingSenderId: '873399511180',
    projectId: 'flutter-crud-64a1f',
    storageBucket: 'flutter-crud-64a1f.appspot.com',
    iosBundleId: 'com.example.flutterCrud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBO8DGvWMY1vfZ6TV2rwtI8is7gYxejm44',
    appId: '1:873399511180:ios:a62308e3d223b9bf2d33a9',
    messagingSenderId: '873399511180',
    projectId: 'flutter-crud-64a1f',
    storageBucket: 'flutter-crud-64a1f.appspot.com',
    iosBundleId: 'com.example.flutterCrud',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAFJirKtKGe_kqiElReHdo4rtn3tdlQxYE',
    appId: '1:873399511180:web:908010f3619d4fa62d33a9',
    messagingSenderId: '873399511180',
    projectId: 'flutter-crud-64a1f',
    authDomain: 'flutter-crud-64a1f.firebaseapp.com',
    storageBucket: 'flutter-crud-64a1f.appspot.com',
  );
}
